---
title: "AfricanRegions"
author: "Armand Bester"
date: "11 September 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<br>

#### On behalve of the authors of the work:
### Application of sero-epidemiology data to informing interventions for HBV in Africa: should diagnosis and treatment replace catch-up vaccination?

<br>


#### Load some handy libraries
```{r libs}
library(readxl)
library(dplyr)
library(ggplot2)
library(leaflet)
library(readr)
library(ggmap)
library(maptools)
library(rgeos)
library(scales)
library(RColorBrewer)
library(gpclib)
library(gridExtra)


```

<br>


#### Create coutry/region lookup table from Anna's data

```{r getData}
countries_regions <- read_delim("AfricaHBV_update.csv", col_names = TRUE, delim = "|")
countries_regions <- countries_regions %>% 
  select(c(Country, African_Region)) %>% 
  unique()

# Due to small differances in the country names, add the 'alternative' spelling to the lookup table
add.df <- data.frame("id" = c("Cote d`Ivoire", "Congo-Brazzaville", "Swaziland", 
                              "Democratic Republic of Congo", "Central African Republic"), 
                     "region" = c("West", "Central", "South", "Central", "Central"))

colnames(add.df) <- c('Country', 'African_Region')

countries_regions <- rbind(countries_regions, add.df)

```

<br>

#### Load the data

```{r}
region_avg.df <- read_excel(path = 'regions.xlsx')

region_avg.df <- merge(countries_regions, region_avg.df, by.x = 'African_Region', by.y = 'Region',  all.x = TRUE)
```


<br>

#### Plotting

<br>

```{r}

# read in the shape file
africa.shp <- readShapeSpatial("Africa_SHP/Africa.shp")

# permit the use for gpclib
gpclibPermit()

# convert the shape file to a dataframe
africa.shp.f <- fortify(africa.shp, region = "COUNTRY")

# merge regional data
merge.shp.coef<-merge(africa.shp.f, region_avg.df, by.x = "id", by.y = 'Country', all.x=TRUE)

# correctly order the polygon data
final.plot<-merge.shp.coef[order(merge.shp.coef$order), ] 



```




```{r}
# plot
fig1G <- ggplot()+
  geom_polygon(data = final.plot,
               aes(x = long, y = lat, group = group, fill = final.plot$HBsAg),
               color = "black", size = 0.2)+
  coord_map()+
  scale_fill_distiller(palette = "Greens", direction = 1, name = "")+
  theme(panel.background = element_blank(), axis.text = element_blank(),
        axis.title = element_blank(), axis.ticks = element_blank())+
  ggtitle("G") + theme(plot.title = element_text(size = 30), legend.text = element_text(size = 20))

fig1G

# plot
fig1H <- ggplot()+
  geom_polygon(data = final.plot,
               aes(x = long, y = lat, group = group, fill = final.plot$`Anti-HBc`),
               color = "black", size = 0.2)+
  coord_map()+
  scale_fill_distiller(palette = "Greens", direction = 1, name = "")+
  theme(panel.background = element_blank(), axis.text = element_blank(),
        axis.title = element_blank(), axis.ticks = element_blank())+
  ggtitle("H") + theme(plot.title = element_text(size = 30), legend.text = element_text(size = 20))

fig1H

# plot
fig1I <- ggplot()+
  geom_polygon(data = final.plot,
               aes(x = long, y = lat, group = group, fill = final.plot$Susceptibles),
               color = "black", size = 0.2)+
  coord_map()+
  scale_fill_distiller(palette = "Greens", direction = 1, name = "")+
  theme(panel.background = element_blank(), axis.text = element_blank(),
        axis.title = element_blank(), axis.ticks = element_blank())+
  ggtitle("I") + theme(plot.title = element_text(size = 30), legend.text = element_text(size = 20))

fig1I

# resources for geoplotting

# http://www.maplibrary.org/library/stacks/Africa/index.htm
# http://rforpublichealth.blogspot.com/2015/10/mapping-with-ggplot-create-nice.html
```



<br>
#### Final figure
<br>

```{r}

# plots = list(fig1G,
#              fig1H,
#              fig1I)
#              
# figure <- grid.arrange(grobs= lapply(plots, "+", theme(plot.margin=margin(1,1,1,1))), 
#                        ncol = 3, nrow = 1)
# 
# figure <- grid.arrange(arrangeGrob(fig1G, fig1H, fig1I, ncol = 3))
# 
# figure

# save the figures seperately and use Inkscape to create the final image
ggsave("fig1G.jpeg", fig1G, dpi = 600, height = 7, width = 7)
ggsave("fig1H.jpeg", fig1H, dpi = 600, height = 7, width = 7)
ggsave("fig1I.jpeg", fig1I, dpi = 600, height = 7, width = 7)



```


<br>
<br>
<br>
<br>
























